
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data/json
      CHROMA_DIR: /app/data/chroma_db
      SQLITE_URL: sqlite:////app/data/clinic.db
      ALLOW_ORIGINS: "*"
      JANEAPP_BASE: "https://demo.janeapp.com"
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      API_BASE: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app 