
version: "3.9"
services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - chroma
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    
  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app

volumes:
  chroma_data: