
version: "3.9"
services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data/json
      # CHROMA_DIR: /app/data/chroma_db
      # SQLITE_URL: sqlite:////app/data/clinic.db
      ALLOW_ORIGINS: "*"
      JANEAPP_BASE: "https://demo.janeapp.com"
      CHROMA_HOST: chroma
      SQL_DB_URL: "postgresql://postgres.zwbytjknnthtwnsddqsx:gJPYFDGAwQPRb43s@aws-1-us-east-1.pooler.supabase.com:6543/postgres"
    depends_on:
      - chroma
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      API_BASE: http://api:8080
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend

volumes:
  chroma_data: